// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHW7khiMEgUvdOMJRCZV2Sx8Bhn-7QYu0',
    appId: '1:200558915853:web:5798d2092e173cd7de0044',
    messagingSenderId: '200558915853',
    projectId: 'chat-app-8df1c',
    authDomain: 'chat-app-8df1c.firebaseapp.com',
    storageBucket: 'chat-app-8df1c.appspot.com',
    measurementId: 'G-9FKJT884D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQojuR9WcBz1eTXSZEueMbi6_zPfn2obM',
    appId: '1:200558915853:android:93a4cb6b9d2b3571de0044',
    messagingSenderId: '200558915853',
    projectId: 'chat-app-8df1c',
    storageBucket: 'chat-app-8df1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZgEgltrZ-IOejZnQhr4UlEy5I57R_vI',
    appId: '1:200558915853:ios:2a2fc26fa30a31f0de0044',
    messagingSenderId: '200558915853',
    projectId: 'chat-app-8df1c',
    storageBucket: 'chat-app-8df1c.appspot.com',
    iosClientId: '200558915853-r9qtrvqaeb1j8pbkim6256jfsqfu34eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEZgEgltrZ-IOejZnQhr4UlEy5I57R_vI',
    appId: '1:200558915853:ios:ce82b787931944d1de0044',
    messagingSenderId: '200558915853',
    projectId: 'chat-app-8df1c',
    storageBucket: 'chat-app-8df1c.appspot.com',
    iosClientId: '200558915853-li5bkg42aehmch0ocbsg7s0o5u1p527t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
